version: '3.0'
services:
  fuseki:
    image: ${IMAGE:-ghcr.io/nfdi4objects/n4o-fuseki}
    ports:
      - "${PORT:-3030}:3030"
    volumes:
      - ./logs:/fuseki/logs
      - ./databases:/fuseki/databases
    #  - ./config.ttl:/fuseki/config.ttl:ro
    #  - ./log4j2.properties:/fuseki/log4j2.properties:ro
    container_name: n4o-fuseki

    # Everything below is only for local development and testing of the image.
    # Please don't copy to your local docker-compose.yml!
    build: # only required to build locally
      context: .
      dockerfile: Dockerfile
