version: '3.0'
services:
  fuseki:
    image: ${IMAGE:-ghcr.io/nfdi4objects/n4o-fuseki}
    build: # only required to build locally
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3030}:3030"
    volumes:
      - ./logs:/fuseki/logs
      - ./databases:/fuseki/databases
    # Uncomment for testing config.ttl
    #  - ./config.ttl:/fuseki/config.ttl:ro
    container_name: n4o-fuseki
